version: '3.5'


networks:

  redis_network:


services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    environment:
      - REDIS_HOST=redis
    ports:
      - "0.0.0.0:5000:80"
    depends_on:
      - redis
    networks:
      - redis_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: worker:latest
    container_name: worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - redis_network

  redis:
    image: redis:5.0.3-alpine3.8
    container_name: redis
    networks:
      - redis_network
